export const GET_ALL_MOVIES = "GET_ALL_MOVIES";
export const SEARCH_MOVIES = "SEARCH_MOVIES";
export const GET_PAGE = "GET_PAGE";

export const MOVIE_DETAILS_REQUEST = "MOVIE_DETAILS_REQUEST";
export const MOVIE_DETAILS_SUCCESS = "MOVIE_DETAILS_SUCCESS";
export const MOVIE_DETAILS_FAIL = "MOVIE_DETAILS_FAIL";
